spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
  docker:
    compose:
      enabled: false
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:db/h2/schema.sql
      data-locations: classpath:db/h2/data.sql
