spring:
  profiles:
    active: h2
  application:
    name: job_description
  datasource:
    url: jdbc:mysql://localhost:3306/job_description
    username: root
    password: root
    hikari: 
      auto-commit: false
  docker:
    compose:
      lifecycle-management: start-and-stop
  h2:
    console:
      enabled: false
  jpa:
    properties:
      hibernate:
        '[format_sql]': true
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: always
      schema-locations: classpath:db/mysql/schema.sql
      data-locations: classpath:db/mysql/data.sql
